title: Лекции
description: Радиоматериалы • Электроника • ОТЦ
author: Студент

# Тема Minima, зафиксированная на конкретном коммите
remote_theme: jekyll/minima@1e8a445

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

minima:
  skin: auto
  date_format: "%d.%m.%Y"
  nav_pages:
    - index.md

show_excerpts: false

# Не даём Jekyll трогать manifest.json
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
